global:
  storageClass: "universal.ru-3b"

ollama:
  enabled: true
  name: rag-p-ollama
  pvcName: rag-p-ollama-models
  image: ollama/ollama:0.4.7
  model: bge-m3
  storage:
    size: 10Gi
    storageClass: "universal.ru-3b"
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 2Gi
