{{- if and .Values.vault.enabled .Values.vault.externalSecrets.s3 }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "rag-p.fullname" . }}-s3-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rag-p.componentLabels" (dict "root" . "component" "s3") | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "rag-p.fullname" . }}-vault
    kind: ClusterSecretStore
  target:
    name: cnpg-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: rag-p/s3
        property: access_key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: rag-p/s3
        property: secret_key
{{- end }}
