{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "rag-p.fullname" . }}-vault
  labels:
    {{- include "rag-p.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: "http://{{ .Release.Name }}-vault.{{ .Release.Namespace }}:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "rag-p-secrets"
          serviceAccountRef:
            name: {{ include "rag-p.fullname" . }}-eso-sa
            namespace: {{ .Release.Namespace }}
{{- end }}
