apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag-p.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rag-p.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
data:
  {{- range $key, $value := .Values.web.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
